############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Contact"
url = "/contact/"
weight = 2
# hasChildren = true


[[main]]
name = "About"
# url = "about/"
weight = 9

  [[main]]
  parent = "About"
  name = "About Us"
  url = "/about/"
  weight = 90

  [[main]]
  parent = "About"
  name = "Tags"
  url = "/tags/"
  weight = 91

  [[main]]
  parent = "About"
  name = "Categories"
  url = "/categories/"
  weight = 92



[[main]]
name = "Activities"
weight = 3


  [[main]]
  parent = "Activities"
  name = "Training"
  url = "/training/"
  weight = 31

  [[main]]
  parent = "Activities"
  name = "Harvest"
  url = "/harvest/"
  weight = 32

  [[main]]
  parent = "Activities"
  name = "Others"
  url = "/others/"
  weight = 33


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
