#################### default parameters ################################
favicon = "icons/main.png"
logo = "icons/main.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "80x"
# logo text will only show when logo is missing.
logo_text = "Unlad Saka"
navbar_fixed = false
description = "Unlad Saka is an association of farmers"
# author = "Themefisher"
image = "icons/main.png" # this image will be used as fallback if a page has no image of its own
# address = ""
# mobile = ""
email = "unlad@pantrypoints.com"
contact_form_action = "#" # contact form works with https://formspree.io
search = true

# Posts related Titles & Contents
categories_title = "Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
read_more_button = "Read more"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = ""
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["news", "harvest", "trainings", 'others']
# about widget content
about_widget_content = "Unlad Saka"
footer_content = "Let's Help Farmers!"
custom_script= ""
theme_copyright = true
copyright = "Copyright 2023 | Unlad Saka"

# 404
error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Let's Help Farmers!"
title_small = ""
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
# content = "or donate to a charity."
button_label = "Register"
button_link = "https://hub.pantrypoints.com/signup"
button_label2 = "Donate or Send a Message"
button_link2 = "/contact/"

# Advertise
[advertisement]
image = "banners/dd.jpg"
link = "https://play.google.com/store/apps/details?id=com.pantrypoints.farmsolo"


# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
newsletter_title = "Stay Updated"
newsletter_invitation = "Join Unlad Saka by sending your email or contact number with country code below"
newsletter_placeholder = "john@company.com"
newsletter_reminder_a = "Check out our"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Send"
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "website"
icon = "fas fa-globe-asia" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://unlad.pantrypoints.com"


[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/unladsakaph"

# [[social]]
# title = "twitter"
# icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
# link = "https://twitter.com/unladsaka"


# [[social]]
# title = "youtube"
# icon = "fab fa-youtube" # themify icon : https://themify.me/themify-icons
# link = "https://www.youtube.com/@unladsaka"

# [[social]]
# title = "github"
# icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"

# [[social]]
# title = "linkedin"
# icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"
